
#─────────────────────────────────────────────────────────────────────────
# Anywhere that uses item IDs also supports:
# • Tags (e.g. "#minecraft:planks")
# • Comma-separated lists (e.g. "minecraft:blaze_powder,#forge:rods/blaze")
#     Applies the setting to all listed IDs. Can use tags, regular IDs, and negation interchangeably
# • Negation (e.g. "!minecraft:black_dye")
#     Useful with lists/tags. Excludes the listed IDs from the setting
#     i.e. "#forge:dyes,!minecraft:black_dye" (all dyes EXCEPT black dye)
# Settings with "//v" will list elements vertically. Removing "//v" will list elements in one line
#─────────────────────────────────────────────────────────────────────────
#─────────────────────────────────────────────────────────────────────────
# Defines items that can be used as fuel
# └── Format: [["item_id", amount], [...], etc]
# • item_id: The item's ID (i.e. "minecraft:coal").
# • amount: The amount of fuel the item provides. Higher values mean the item burns longer
# ⌄ 
["Fuel Items"]
	#─────────────────────────────────//v
	Boiler = [
	    ["#minecraft:planks", 50],
	    ["minecraft:coal", 185],
	    ["#forge:coal_coke", 925],
	    ["minecraft:charcoal", 185],
	    ["#minecraft:logs_that_burn", 185],
	    ["minecraft:coal_block", 1665],
	    ["minecraft:magma_block", 1665],
	    ["minecraft:lava_bucket", 5000],
	    ["minecraft:dried_kelp_block", 92]
	]
	#─────────────────────────────────//v
	Icebox = [
	    ["minecraft:snowball", 50],
	    ["minecraft:clay_ball", 185],
	    ["minecraft:snow_block", 500],
	    ["minecraft:ice", 1250],
	    ["minecraft:clay", 1665],
	    ["minecraft:powder_snow_bucket", 500],
	    ["minecraft:packed_ice", 5000],
	    ["minecraft:blue_ice", 10000]
	]
	#─────────────────────────────────//v
	# (Negative values indicate cold fuel
	Hearth = [
	    ["#minecraft:planks", 50],
	    ["minecraft:coal", 185],
	    ["minecraft:charcoal", 185],
	    ["#minecraft:logs_that_burn", 185],
	    ["minecraft:coal_block", 1665],
	    ["minecraft:magma_block", 1665],
	    ["minecraft:lava_bucket", 5000],
	    ["minecraft:snowball", -50],
	    ["minecraft:clay_ball", -185],
	    ["minecraft:snow_block", -500],
	    ["minecraft:ice", -1250],
	    ["minecraft:clay", -1665],
	    ["minecraft:powder_snow_bucket", -500],
	    ["minecraft:packed_ice", -5000],
	    ["minecraft:dried_kelp_block", 92]
	]

["Soulspring Lamp"]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that the Soulspring Lamp can use as fuel
	# └── Format: [["item_id", amount], [...], etc]
	# • item_id: The item's ID (i.e. "cold_sweat:soul_sprout").
	# • amount: The amount of fuel the item provides. Higher values mean the item burns longer
	# ⌄ 
	"Fuel Items" = [
	    ["cold_sweat:soul_sprout", 4]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the dimensions that the Soulspring Lamp can be used in
	# └── Format: ["dimension_id", "dimension_id", ...etc]
	# ⌄ 
	"Valid Dimensions" = [
	    "minecraft:the_nether"
	]

[Insulation]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the items that can be used for insulating armor in the Sewing Table
	# ├── Format (Static): [["item_id", cold, heat, *"static", *"{nbt}", *fillSlots], [...], etc]
	# ├── Format (Adaptive): [["item_id", amount, adaptSpeed, "adaptive", *"{nbt}", *fillSlots], [...], etc]
	# └── [* = optional]
	# • item_id: The item's ID (i.e. "minecraft:iron_ingot").
	# • cold: The cold insulation the item provides.
	# • heat: The heat insulation the item provides.
	# • amount: The amount of insulation the item provides.
	# • adaptSpeed: The speed at which the insulation adapts to the environment.
	# • *static/adaptive: The type of insulation the item provides. Defaults to "static" if unset
	# • *nbt: If set, the item will only provide insulation if it has the specified NBT tag.
	# • *fillSlots: If true, the item will fill 1 slot per 2 insulation points. Otherwise, the item will fill 1 slot.
	# ⌄ 
	"Insulation Ingredients" = [
	    ["blue_skies:chilled_lily_pad", 0.0, 4.0, "static", "", true],
	    ["galosphere:cured_membrane", 1.5, 2.0, "static", "", true],
	    ["ars_nouveau:magebloom_fiber", 5.5, 0.03, "adaptive", "", true],
	    ["minecraft:red_wool", 1.5, 0.0, "static", "", true],
	    ["ecologics:coconut_husk", 1.5, 0.0, "static", "", true],
	    ["cold_sweat:chameleon_molt", 2.0, 0.0085, "adaptive", "", true],
	    ["undergarden:mogmoss", 0.0, 11.0, "static", "", true],
	    ["minecraft:light_gray_wool", 1.5, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_amythest", 9.0, 9.0, "static", "", true],
	    ["minecraft:white_wool", 1.5, 0.0, "static", "", true],
	    ["minecraft:brown_wool", 1.5, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_green", 18.0, 0.0, "static", "", true],
	    ["minecraft:black_wool", 1.5, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_copper", 9.0, 9.0, "static", "", true],
	    ["farmersdelight:straw", 1.0, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_bronze", 18.0, 0.0, "static", "", true],
	    ["iceandfire:ice_dragon_blood", 2.0, 16.0, "static", "", true],
	    ["cold_sweat:hoglin_hide", 0.0, 2.0, "static", "", true],
	    ["immersiveengineering:hemp_fabric", 2.0, 2.0, "static", "", true],
	    ["irons_spellbooks:magic_cloth", 7.0, 7.0, "static", "", true],
	    ["iceandfire:dragonscales_silver", 0.0, 18.0, "static", "", true],
	    ["architects_palette:algal_blend", 4.0, 0.0, "static", "", true],
	    ["outer_end:spectragel", 8.0, 0.01, "adaptive", "", true],
	    ["alexsmobs:kangaroo_hide", 10.0, 0.0, "static", "", true],
	    ["minecraft:leather", 1.0, 1.0, "static", "", true],
	    ["alexsmobs:mimicream", 8.0, 0.5, "adaptive", "", true],
	    ["iceandfire:dragonscales_blue", 0.0, 18.0, "static", "", true],
	    ["eidolon:tattered_cloth", 3.5, 2.5, "static", "", true],
	    ["ecologics:surface_moss", 1.0, 0.0, "static", "", true],
	    ["tetra:vent_plate", 10.0, 0.0, "static", "", true],
	    ["minecraft:green_wool", 1.5, 0.0, "static", "", true],
	    ["alexscaves:tough_hide", 16.0, 0.0, "static", "", true],
	    ["minecraft:blue_wool", 1.5, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_red", 18.0, 0.0, "static", "", true],
	    ["cataclysm:dying_ember", 20.0, 0.0, "static", "", true],
	    ["minecraft:magenta_wool", 1.5, 0.0, "static", "", true],
	    ["iceandfire:lightning_dragon_blood", 9.0, 9.0, "static", "", true],
	    ["minecraft:lime_wool", 1.5, 0.0, "static", "", true],
	    ["occultism:tallow", 3.5, 0.0, "static", "", true],
	    ["minecraft:light_blue_wool", 1.5, 0.0, "static", "", true],
	    ["minecraft:purple_wool", 1.5, 0.0, "static", "", true],
	    ["minecraft:gray_wool", 1.5, 0.0, "static", "", true],
	    ["minecraft:orange_wool", 1.5, 0.0, "static", "", true],
	    ["cataclysm:amethyst_crab_shell", 10.0, 6.0, "static", "", true],
	    ["iceandfire:dragonscales_white", 0.0, 18.0, "static", "", true],
	    ["alexsmobs:bear_fur", 8.0, 0.0, "static", "", true],
	    ["undergarden:ditchbulb_paste", 4.0, 8.0, "static", "", true],
	    ["cold_sweat:goat_fur", 2.0, 0.0, "static", "", true],
	    ["minecraft:cyan_wool", 1.5, 0.0, "static", "", true],
	    ["forbidden_arcanus:cloth", 3.0, 3.0, "static", "", true],
	    ["eidolon:wicked_weave", 6.5, 6.5, "static", "", true],
	    ["alexscaves:polymer_plate", 12.0, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_sapphire", 0.0, 18.0, "static", "", true],
	    ["blue_skies:moonlit_water_lily", 0.0, 10.5, "static", "", true],
	    ["architects_palette:cerebral_plate", 0.0, 5.0, "static", "", true],
	    ["minecraft:pink_wool", 1.5, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_electric", 9.0, 9.0, "static", "", true],
	    ["eidolon:tallow", 3.5, 0.0, "static", "", true],
	    ["undergarden:blue_mogmoss", 9.0, 1.0, "static", "", true],
	    ["aquamirae:fin", 2.0, 2.0, "static", "", true],
	    ["alexscaves:dark_tatters", 5.0, 0.03, "adaptive", "", true],
	    ["iceandfire:dragonscales_gray", 18.0, 0.0, "static", "", true],
	    ["hexerei:wax_blend", 6.0, 0.0, "static", "", true],
	    ["iceandfire:dragonscales_black", 9.0, 9.0, "static", "", true],
	    ["minecraft:yellow_wool", 1.5, 0.0, "static", "", true],
	    ["undergarden:blood_globule", 4.5, 0.005, "adaptive", "", true],
	    ["minecraft:rabbit_hide", 0.0, 1.5, "static", "", true],
	    ["iceandfire:fire_dragon_blood", 16.0, 2.0, "static", "", true],
	    ["architects_palette:sunmetal_blend", 0.0, 7.5, "static", "", true],
	    ["blue_skies:fox_pelt", 10.0, 2.0, "static", "", true],
	    ["forbidden_arcanus:nipa", 5.5, 5.5, "static", "", true],
	    ["nomowanderer:trader_cloth_piece", 4.0, 4.0, "static", "", true],
	    ["caverns_and_chasms:living_flesh", 4.8, 0.005, "adaptive", "", true],
	    ["environmental:yak_hair", 10.0, 0.0, "static", "", true],
	    ["environmental:yak_hair_block", 14.0, 0.0, "static", "", true],
	    ["environmental:mud_ball", 0.0, 4.0, "static", "", true],
	    ["galosphere:glow_ink_clumps", 0.0, 5.0, "static", "", true],
	    ["farmersdelight:canvas", 2.0, 5.0, "static", "", true],
	    ["blue_skies:soul_fragment", 0.0, 11.0, "static", "", true],
	    ["blue_skies:star_flare", 0.0, 11.0, "static", "", true],
	    ["minecells:monster_cell", 7.0, 0.1, "static", "", true],
	    ["quark:moss_paste", 0.0, 6.0, "static", "", true],
	    ["miners_delight:moss", 0.0, 6.0, "static", "", true],
	    ["ecologics:surface_moss", 0.0, 4.0, "static", "", true],
	    ["forbidden_arcanus:stellarite_piece", 9.0, 9.0, "static", "", true],
	    ["forbidden_arcanus:eternal_stella", 10.0, 0.2, "adaptive", "", true],
	    ["forbidden_arcanus:obsidian_ingot", 0.0, 7.5, "static", "", true],
	    ["blue_skies:aquite", 0.0, 9.0, "static", "", true],
	    ["blue_skies:pyrope_gem", 9.0, 0.0, "static", "", true],
	    ["neapolitan:ice_cubes", 0.0, 4.0, "static", "", true],
	    ["thermal:blizz_rod", 0.0, 12.0, "static", "", true],
	    ["irons_spellbooks:frozen_bone", 0.0, 3.0, "static", "", true],
	    ["thermal:blitz_rod", 6.0, 6.0, "static", "", true],
	    ["thermal:basalz_rod", 12.0, 0.0, "static", "", true],
	    ["minecraft:blaze_rod", 13.0, 0.0, "static", "", true],
	    ["alexscaves:radiant_essence", 5.5, 0.15, "adaptive", "", true],
	    ["irons_spellbooks:cinder_essence", 13.0, 0.0, "static", "", true],
	    ["immersiveengineering:ersatz_leather", 5.0, 5.0, "static", "", true]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the items that provide insulation when worn
	# ** See Insulation Ingredients for formatting.
	# Enabling "fillSlots" will cause the armor's built-in insulation to consume the available insulation slots
	# i.e. if an item has 5 insulation slots and gives one slot of cold insulation by default, it will only have 4 free slots left
	# ⌄ 
	"Insulating Armor" = [
	    ["minecraft:leather_boots", 5, 5],
	    ["cold_sweat:hoglin_hooves", 0, 10],
	    ["minecraft:leather_helmet", 5, 5],
	    ["cold_sweat:hoglin_tunic", 0, 14],
	    ["minecraft:leather_leggings", 6, 6],
	    ["cold_sweat:hoglin_headpiece", 0, 10],
	    ["cold_sweat:goat_fur_parka", 14, 0],
	    ["minecraft:leather_chestplate", 7, 7],
	    ["cold_sweat:goat_fur_pants", 12, 0],
	    ["cold_sweat:hoglin_trousers", 0, 12],
	    ["cold_sweat:goat_fur_cap", 10, 0],
	    ["cold_sweat:goat_fur_boots", 10, 0],
	    ["minecraft:netherite_helmet", 0.0, 10.0, "static", "{}"],
	    ["minecraft:netherite_chestplate", 0.0, 10.0, "static", "{}"],
	    ["minecraft:netherite_leggings", 0.0, 10.0, "static", "{}"],
	    ["minecraft:netherite_boots", 0.0, 10.0, "static", "{}"],
	    ["cold_sweat:chameleon_scale_helmet", 10, 0.0085, "adaptive"],
	    ["cold_sweat:chameleon_scale_chestplate", 14, 0.0085, "adaptive"],
	    ["cold_sweat:chameleon_scale_leggings", 12, 0.0085, "adaptive"],
	    ["cold_sweat:chameleon_scale_boots", 10, 0.0085, "adaptive"]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the items that provide insulation when worn in a curio slot
	# See Insulation Ingredients for formatting. This setting does not have a "fillSlots" option
	# ⌄ 
	"Insulating Curios" = [
	    ["aether:leather_gloves", 4.0, 4.0, "static", "{}"],
	    ["artifacts:fire_gauntlet", 5.0, 0.0, "static", "{}"],
	    ["relics:rage_glove", 2.0, 0.0, "static", "{}"],
	    ["relics:ice_skates", 0.0, 3.0, "static", "{}"],
	    ["relics:wool_mitten", 1.5, 0.0, "static", "{}"],
	    ["relics:magma_walker", 4.0, 0.0, "static", "{}"],
	    ["minecraft:lantern", 2.0, 0.0, "static", "{}"],
	    ["enigmaticlegacy:ocean_stone", 0.0, 12.0, "static", "{}"],
	    ["enigmaticlegacy:blazing_core", 12.0, 0.0, "static", "{}"],
	    ["traveloptics:fire_echo", 4.0, 0.0, "static", "{}"],
	    ["traveloptics:ice_echo", 0.0, 4.0, "static", "{}"],
	    ["traveloptics:aqua_echo", 2.0, 2.0, "static", "{}"]
	]
	#─────────────────────────────────────────────────────────────────────────
	# Defines how many insulation slots armor pieces have
	# There are 4 modes for this setting:
	# ┌ Static: Each armor slot (head, body, legs, feet) has a fixed number of insulation slots
	# └─── Format: [head, body, legs, feet]
	#      • head/body/legs/feet: The number of insulation slots for that armor slot
	# ┌ Linear: Number of slots increases steadily with protection
	# ├ Exponential: Number of slots increases exponentially with protection
	# ├ Logarithmic: Number of slots increases with protection, with diminishing returns
	# └─── Format: [multiplier, max-slots]
	#      • multiplier: Multiplied by the armor's protection value to get the number of insulation slots
	#      • max-slots: The maximum number of insulation slots an armor piece can have
	# ⌄ 
	"Insulation Slots" = ["logarithmic", 3.9, +inf]
	#─────────────────────────────────────────────────────────────────────────
	# Defines the effectiveness of insulating items in protecting against temperature
	# ⌄ 
	#Range: 0.0 ~ Infinity
	"Insulation Strength" = 1.0
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines wearable items that cannot be insulated
	# └── Format: ["item_id", "item_id", ...etc]
	# ⌄ 
	"Insulation Blacklist" = []
	#─────────────────────────────────────────────────────────────────────────//v
	# Allows for overriding the number of insulation slots for specific items
	# └── Format: [["item_id", slotCount, *"{nbt}"], ["item_id", slotCount, *"{nbt}"], [...], etc]
	# • item_id: The item's ID (i.e. "minecraft:iron_helmet").
	# • slot_count: The number of insulation slots the item should have.
	# • *nbt: If set, the item will only have the specified number of insulation slots if it has the specified NBT tag.
	# ⌄ 
	"Insulation Slot Overrides" = []

[Consumables]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that affect the player's temperature when consumed
	# ├── Format: [["item_id", amount, *"{nbt}", *duration], ["item_id", amount, *"{nbt}", *duration], ...etc]
	# └── [* = optional]
	# • item_id: The item's ID (i.e. "minecraft:apple").
	# • amount: The amount to change the player's temperature by. Negative values are cold, positive values are hot
	# • *nbt: If set, the item will only affect the player's temperature if it has the specified NBT tag.
	# • *duration: If set, the player's temperature will remain increased/decreased for this amount of time (in ticks).
	# ⌄ 
	"Temperature-Affecting Foods" = [
	    ["cold_sweat:soul_sprout", -20.0, "{}", 1200]
	]
	#─────────────────────────────────────────────────────────────────────────
	# Defines how much a waterskin will change the player's body temperature when used
	# ⌄ 
	#Range: > 0
	"Waterskin Strength" = 50
	#─────────────────────────────────────────────────────────────────────────
	# Determines the strength of the Soulspring Lamp's effect before it is overwhelmed
	# A value of 1 means it will never be overwhelmed
	# ⌄ 
	#Range: 0.0 ~ 1.0
	"Soulspring Lamp Strength" = 0.6
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that can be used to dry the player
	# └── Format: [["item_id", "turns_into"], [...], etc]
	# • item_id: The item's ID (i.e. "minecraft:sponge").
	# • turns_into: The item to be turned into when the item is used (i.e. "minecraft:wet_sponge").
	# ⌄ 
	"Drying Items" = []
	#─────────────────────────────────────────────────────────────────────────
	# A multiplier for how effective a waterskin's over-time effect is, when held in the player's hotbar
	# ⌄ 
	#Range: 0.0 ~ Infinity
	"Waterskin Hotbar Strength" = 1.0
	#─────────────────────────────────────────────────────────────────────────
	# A multiplier for how quickly a waterskin will return to its neutral temperature when being used in the hotbar
	# ⌄ 
	#Range: 0.0 ~ Infinity
	"Waterskin Neutralize Speed" = 1.0
	#─────────────────────────────────────────────────────────────────────────
	# Defines how many times a waterskin can be used before becoming empty
	# ⌄ 
	#Range: > 1
	"Waterskin Uses" = 1

[Misc]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that affect the player's temperature when in the inventory
	# ├── Format: [["item_id", temperature, "slotRange", "trait", *"{nbt}", *maxEffect, *tempLimit], [...], etc]
	# └── [* = optional]
	# • item_id: The item's ID (i.e. "minecraft:lava_bucket").
	# • temperature: The temperature change the item will apply to the entity. For core temperature, this is applied every tick
	# • slot_range: Either "inventory", "hotbar", or "hand". Defines what slots the item must be in to apply to the entity (inventory includes hotbar)
	# • trait: The temperature trait to apply the effect to. Typical values are "core" for body temperature or "world" for ambient temperature. More on the mod documentation page.
	# • *nbt: The NBT data the item must have to apply to the entity.
	# • *max_effect: The maximum temperature effect the item can apply to the entity.
	# • *tempLimit: The maximum temperature at which this item temp will have any effect.
	#   (Based on the given trait. Represents the minimum temp if the item temp is negative)
	# ⌄ 
	"Item Temperatures" = []

# Drains pressure from Create's netherite backtank if the player is in a hot/cold environment
# Triggered by the set bonus for wearing a full set of netherite diving gear
# Disabling these settings will not disable the heat/cold protection set bonus
# ⌄ 
["Create Backtank"]
	"Heat Drains Backtank" = true
	"Cold Drains Backtank" = false

["Hearth Extras"]
	#─────────────────────────────────────────────────────────────────────────//v
	# Potions containing any of these effects will not be allowed in the hearth
	# └── Format: ["effect_id", "effect_id", ...etc]
	# ⌄ 
	"Blacklisted Hearth Potions" = [
	    "minecraft:instant_damage",
	    "minecraft:poison",
	    "minecraft:wither",
	    "minecraft:weakness",
	    "minecraft:mining_fatigue",
	    "minecraft:slowness"
	]
	#─────────────────────────────────────────────────────────────────────────
	# If true, potions can be used in the hearth to give all players in range the potion effect
	# ⌄ 
	"Allow Potions in Hearth" = true

["Item Functions"]
	#─────────────────────────────────────────────────────────────────────────
	# Allow fire resistance to block overheating damage
	# ⌄ 
	"Fire Resistance Immunity" = true
	#─────────────────────────────────────────────────────────────────────────
	# Allow ice resistance to block freezing damage
	# ⌄ 
	"Ice Resistance Immunity" = true
	#─────────────────────────────────────────────────────────────────────────
	# Whether a thermometer is required to see exact world and body temperature
	# ⌄ 
	"Require Thermometer" = true

