
[slicer]
	consume_tool_durability = true
	ignore_rotation = false
	jei_show_converted_recipes = false

[basin_cooking]
	enabled = true
	replace_fluid_containers = true
	#Allowed Values: NONE, HEATED, SUPERHEATED
	heat_condition = "HEATED"

[sprinkler]
	#Range: 10 ~ 2048
	fluid_capacity = 300
	#Range: 0 ~ 2048
	fluid_per_use = 100
	#Range: 1 ~ 32
	horizontal_range = 5

[harvester]
	uses_knife = true

