
#Common Configs || This config file offer controls to many different things on the mod.
#Changing something you don't know about, might break your game.
[common]

	[common.general]
		#Show welcome message || Default: true
		welcome_message = false

	[common.effect]
		#List of effect IDs that are immune to Rainfall cleanse || Example: ["minecraft:blindness", "minecraft:darkness"]
		rainfall_immune_effects = []
		#List of effect IDs that are immune to Acid Rain cleanse || Example: ["minecraft:absorption", "minecraft:health_boost"]
		acid_rain_immune_effects = []

